### ISSUE TITLE
Problem when running ready_to_localize

### ISSUE THREAD

**Issue by florianspy** [pozyxLabs/Pozyx-Arduino-library#76]
I am working with Ubuntu 16.04 when i start the ready_to_localize.py file i get the following error message:
('Anchor IDs: ', <pypozyx.structures.device.DeviceList object at 0x7fe601b2e610>)
ANCHOR, 0x6978, X: -1090, Y: -1680, Z: 2150
Traceback (most recent call last):
  File "./ready_to_localize.py", line 171, in <module>
    r.setup()
  File "./ready_to_localize.py", line 48, in setup
    self.printPublishConfigurationResult()
  File "./ready_to_localize.py", line 126, in printPublishConfigurationResult
    "/anchor", [device_list[i], int(anchor_coordinates.x), int(anchor_coordinates.y), int(anchor_coordinates.z)])
  File "/usr/local/lib/python2.7/dist-packages/pythonosc/udp_client.py", line 42, in send_message
    msg = builder.build()
  File "/usr/local/lib/python2.7/dist-packages/pythonosc/osc_message_builder.py", line 164, in build
    return osc_message.OscMessage(dgram)
  File "/usr/local/lib/python2.7/dist-packages/pythonosc/osc_message.py", line 22, in __init__
    self._parse_datagram()
  File "/usr/local/lib/python2.7/dist-packages/pythonosc/osc_message.py", line 78, in _parse_datagram
    raise ParseError('Found incorrect datagram, ignoring it', pe)
pythonosc.osc_message.ParseError: ('Found incorrect datagram, ignoring it', ParseError('Could not parse datagram string index out of range',))

What maybe the reason?

**Comment by laurentva** [comment]
Hello Florian,

You're using Python 2, while the OSC functionality explicitly requires Python 3. Is there a specific reason for you to use Python 2? Otherwise, you can use  `pip3 install pypozyx` and
`python3 ready_to_localize.py` to get it to work.

Also, this is the Arduino library, not the Python library, oops!
